// Code generated by gen/samples_generator.go; DO NOT EDIT.
package sample_wave_structs

import "github.com/yut-kt/gowave/internal/chunk"

func GetRiffChunk() *chunk.RiffChunk {
	return &chunk.RiffChunk{
		ID:     "RIFF",
		Size:   1,
		Format: "WAVE",
	}
}

func GetFmtChunk() *chunk.FmtChunk {
	return &chunk.FmtChunk{
		ID:            "fmt ",
		Size:          16,
		AudioFormat:   1,
		NumChannels:   1,
		SampleRate:    8000,
		ByteRate:      16000,
		BlockAlign:    2,
		BitsPerSample: 16,
	}
}

func GetDataChunk() *chunk.DataChunk {
	return &chunk.DataChunk{
		ID:   "data",
		Size: 0,
		Data: nil,
	}
}
